# This is a basic workflow to help you get started with Actions

name: current_dev_build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "development" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  start-tests:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

     # Install Pester 
      - name: Install Pester
        run:
          $ErrorActionPreference = 'Stop';
          Write-host $PSVersionTable.PSVersion.Major $PSVersionTable.PSRemotingProtocolVersion.Minor;
          Set-PSRepository psgallery -InstallationPolicy trusted;
          Install-Module -Name Pester -RequiredVersion 5.0.4 -Confirm:$false -Force;
          Write-Host "Success";
        shell: powershell

     # Install Supporting Modules 
      - name: Install Supporting Modules
        run:
          $ErrorActionPreference = 'Stop';
          Install-Module 'powershell-yaml';
          Write-Host "Success";
        shell: powershell

      - name: InvokePesterTests
        run: |
          .\Tests\Invoke-Tests.ps1 -CI;
          if ($Error[0].Fullyqualifiederrorid -eq 'PesterAssertionFailed') { exit 1 }
        shell: powershell
